# Generated by Django 6.0.1 on 2026-01-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_remove_issue_assigned_to_issue_assigned_to_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='assigned_to_id',
            new_name='assigned_to',
        ),
    ]
