# Generated by Django 5.2.13 on 2026-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_rename_assigned_to_id_issue_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('BROKEN_SIGN', 'Broken Road Sign'), ('DAMAGED_STRUCTURE', 'Damaged Structure'), ('ELECTRICAL', 'Electrical Issue'), ('FALLEN_TREE', 'Fallen Tree'), ('GARBAGE', 'Garbage'), ('GRAFFITI', 'Graffiti'), ('ROAD_DAMAGE', 'Road Damage'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
