# Generated by Django 5.2.13 on 2026-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='address_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
